config/routes.rb
Moneyplan2013::Application.routes.draw do
  resources :details

  resources :articles

  resources :kinds do
    collection do
      get :get_buttons
    end
  end

  resources :groups do
    collection do
      get :get_buttons
    end
  end

end

app/models/article.rb
# 
class Article < ActiveRecord::Base
  attr_accessible :name
end

app/models/detail.rb
# 明細
class Detail < ActiveRecord::Base
  attr_accessible :group_id, :kind_id, :article, :price

  belongs_to :group
  belongs_to :kind

end

app/models/group.rb
# 分類
class Group < ActiveRecord::Base
  attr_accessible :name
end

app/models/kind.rb
# 種類
class Kind < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

  def index
    @groups = Group.all
    @kinds = Kind.all
    @details = Detail.all

    @group = Group.new()
    @kind = Kind.new()
    @detail = Detail.new()
  end

  def create
    @detail = Detail.new(params[:detail])
    @detail.save

    redirect_to  :action => :index
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  def index
    @groups = Group.all
  end

  def create
    @group = Group.new(params[:group])
    @group.save

    render "create.js.erb"
  end

  def get_buttons
    @groups = Group.all
    render :partial => "buttons_list"
  end

end

app/controllers/kinds_controller.rb
class KindsController < ApplicationController

  def index
    @kinds = Kind.all
  end

  def create
    @kind = Kind.new(params[:kind])
    @kind.save

    render "create.js.erb"
  end

  def get_buttons
    @kinds = Kind.all
    render :partial => "buttons_list"
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/details_helper.rb
module DetailsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/kinds_helper.rb
module KindsHelper
end

app/views/details/_form.html.erb
<%= form_for(@detail, :html =>{:class=>"form-horizontal"}) do |f| %>

  <fieldset>
    <legend>何買ったの？</legend>
    
    <div class="control-group">
      <label class="control-label" for="focusedInput">カテゴリ</label>
      <div class="controls">
        <div id="open_groups" class="label label-info" style="cursor:pointer;">選ぶ？</div>
        <%= f.hidden_field :group_id, :id => "selected_group_id" %>
        <span id="selected_group_name" style="font-size:large;"></span>
        <!-- 分類ボタン一覧 -->
        <div id="group_buttons" style="display:none">
          <%= render 'groups/buttons' %>
        </div>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="focusedInput">種類</label>
      <div class="controls">
        <div id="open_kinds" class="label label-info" style="cursor:pointer;">選ぶ？</div>
        <%= f.hidden_field :kind_id, :id => "selected_kind_id" %>
        <span id="selected_kind_name" style="font-size:large;"></span>
        <!-- 種類ボタン一覧 -->
        <div id="kind_buttons" style="display:none">
          <%= render 'kinds/buttons' %>
        </div>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="focusedInput">商品名</label>
      <div class="controls">
        <%= f.text_field :article %>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label" for="focusedInput">金額</label>
      <div class="controls">
        <%= f.text_field :price %>
      </div>
    </div>
  
    <div class="form-actions">
      <%= f.submit "登録", :class => "btn btn-primary" %>
      <button type="reset" class="btn">キャンセル</button>
    </div>

  </fieldset>


<% end %>





<%= render 'groups/create_dialog' %>
<%= render 'kinds/create_dialog' %>

app/views/details/_list.html.erb
<table class="table table-condensed">
  <thead>
    <tr>
      <th>カテゴリ</th>
      <th>種類</th>
      <th>商品名</th>
      <th>金額</th>
    </tr>
  </thead>

  <tbody>
    <% @details.each do |detail| %>
      <tr>
        <td><%= detail.group.blank? ? "" : detail.group.name %></td>
        <td><%= detail.kind.blank? ? "" : detail.kind.name %></td>
        <td><%= detail.article.blank? ? "" : detail.article %></td>
        <td><%= detail.price.blank? ? "" : detail.price %></td>
      </tr>
    <% end %>
  </tbody>

</table>

app/views/details/index.html.erb
<div class="container" style="margin-left:10px;">
  <div class="row">

    <div class="span8">
    <!-- 画面左側 -->
      <%= render 'form' %>
    </div>

    <div class="span4">
    <!-- 画面右側 -->
      <%= render 'list' %>
    </div>

  </div>
</div>

app/views/details/new.html.erb
<h1>New detail</h1>

<%= render 'form' %>

<%= link_to 'Back', details_path %>




<div id="group">

  <%= render 'groups/buttons' %>

</div>


<div id="kind">

  <%= render 'kinds/form' %>

</div>

app/views/groups/_buttons.html.erb
<div style="width:200px">

  <input type="button" class="btn btn-mini btn-success" value="ないので登録する" onclick="open_group_create_dialog()" />
  <br /><br />

  <div id="group_buttons_list">
    <%= render 'groups/buttons_list' %>
  </div>

</div>

app/views/groups/_buttons_list.html.erb
  <% if @groups.size > 0 %>
    <% @groups.each do |group| %>
      <input type="button" class="btn" style="margin-bottom:10px;" value="<%= group.name %>" onClick="selected('group', '<%= group.id %>', '<%= group.name %>')" />
    <% end %>
  <% else %>
    <p class="text-info">登録されていません。</p>
  <% end %>

app/views/groups/_create_dialog.html.erb
<!-- グループ登録ダイアログ -->
<div id="group_create_dialog" style="display:none">
  <div id="group_create_massege"></div>

  <%= form_for(@group, :url => {:controller => "groups", :action => "create"}, :html => {:class=>"form-horizontal", :remote => true}) do |f| %>
    <fieldset>

    <div class="control-group">
      <label class="control-label" for="focusedInput">カテゴリ名</label>
      <div class="controls">
        <%= f.text_field :name, :id => "create_group_name", :placeholder => "カテゴリ名を入力" %>
      </div>
<%#
      <label class="checkbox inline">
        <input type="checkbox" id="group_continue" class="input-small" value="continue"> 続けて登録する
      </label>
%>
      <div class="form-actions">
        <%= f.submit "登録", :class => "btn btn-primary" %>
        <input type="button" class="btn" value="キャンセル" onclick="close_group_create_dialog()" />
      </div>
    </fieldset>

  <% end %>

</div>

app/views/groups/create.js.erb
<%#var errors = <%=@errors>;%>
<%#var checked = $("#group_continue").attr("checked");%>

var errors = null;
var checked = 'undefined';

//alert(checked);


if (errors == null) {
  $("#group_create_massege").val("");
  $("#create_group_name").val("");
  close_group_create_dialog();


  // グループ一覧書き換え
  var url = "groups/get_buttons";
//alert("url:" + url);

  $.get(url, {},
    function(data){
      $('#group_buttons_list').find('*').remove();
      $('#group_buttons_list').append(data);
    });






}else{
  $("#group_create_massege").val(errors);
}



if (checked == 'checked') {
  open_group_create_dialog();
}

app/views/kinds/_buttons.html.erb
<div style="width:200px">

  <input type="button" class="btn btn-mini btn-success" value="ないので登録する" onclick="open_kind_create_dialog()" />
  <br /><br />

  <div id="kind_buttons_list">
    <%= render 'kinds/buttons_list' %>
  </div>

</div>

app/views/kinds/_buttons_list.html.erb
  <% if @kinds.size > 0 %>
    <% @kinds.each do |kind| %>
      <input type="button" class="btn" style="margin-bottom:10px;" value="<%= kind.name %>" onClick="selected('kind', '<%= kind.id %>', '<%= kind.name %>')" />
    <% end %>
  <% else %>
    <p class="text-info">登録されていません。</p>
  <% end %>

app/views/kinds/_create_dialog.html.erb
<!-- 種類登録ダイアログ -->
<div id="kind_create_dialog" style="display:none">
  <div id="kind_create_massege"></div>

  <%= form_for(@kind, :url => {:controller => "kinds", :action => "create"}, :html => {:class=>"form-horizontal", :remote => true}) do |f| %>
    <fieldset>

    <div class="control-kind">
      <label class="control-label" for="focusedInput">種類名</label>
      <div class="controls">
        <%= f.text_field :name, :id => "create_kind_name", :placeholder => "種類名を入力" %>
      </div>
<%#
      <label class="checkbox inline">
        <input type="checkbox" id="kind_continue" class="input-small" value="continue"> 続けて登録する
      </label>
%>
      <div class="form-actions">
        <%= f.submit "登録", :class => "btn btn-primary" %>
        <input type="button" class="btn" value="キャンセル" onclick="close_kind_create_dialog()" />
      </div>
    </fieldset>

  <% end %>

</div>

app/views/kinds/create.js.erb
<%#var errors = <%=@errors>;%>
<%#var checked = $("#kind_continue").attr("checked");%>

var errors = null;
var checked = 'undefined';

//alert(checked);


if (errors == null) {
  $("#kind_create_massege").val("");
  $("#create_kind_name").val("");
  close_kind_create_dialog();


  // グループ一覧書き換え
  var url = "kinds/get_buttons";
//alert("url:" + url);

  $.get(url, {},
    function(data){
      $('#kind_buttons_list').find('*').remove();
      $('#kind_buttons_list').append(data);
    });






}else{
  $("#kind_create_massege").val(errors);
}



if (checked == 'checked') {
  open_kind_create_dialog();
}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Moneyplan2013</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>